dist: xenial
group: edge

stages:
  - name: Deployment
    if: branch = dev AND type = push AND fork = false

jobs:
  include:
    - stage: Deployment
      name: Backend Deployment
      language: python
      python: "3.8"
      cache: pip
      before_install:
        - openssl aes-256-cbc -K $encrypted_dd1d8ecd8ae9_key -iv $encrypted_dd1d8ecd8ae9_iv -in messag.txt.enc -out messag.txt -d
        - chmod 400 ./messag.txt
      install:
        - pip install ansible
      script:
        - ansible-playbook playbooks/deploy.yml
