name: NodeJS_CI

on:
  push:
    branches: [dev]

jobs:
  testReact:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: Test using "devtest"
        uses: actions/npm@master
        with:
          args: run devtest
      - name: Build
        uses: actions/npm@master
        with:
          args: run build