name: NodeJS_CI

on:
  push:
    branches: [dev]

jobs:
  testReact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        working-directory: ./hashx_frontend
        run: npm install

      - name: Test React Build
        working-directory: ./hashx_frontend
        run: npm run build
